### ISSUE TITLE
PHP handler check doesn't work with easyapache 4 enabled

### ISSUE THREAD

**Issue by chrisice** [CpanelInc/tech-SSE#19]
readline() on closed filehandle $phpconf_fh at /dev/fd/63 line 668.
Use of uninitialized value $php5handler in scalar chomp at /dev/fd/63 line 674.
Use of uninitialized value $php5handler in string eq at /dev/fd/63 line 675.
Use of uninitialized value $php5handler in string ne at /dev/fd/63 line 679.
Use of uninitialized value $php5handler in concatenation (.) or string at /dev/fd/63 line 679.
[WARN] \* PHP5's handler is .

**Comment by cPLevey** [comment]
```
    sub check_for_phphandler {
        my $phpconf = '/usr/local/apache/conf/php.conf.yaml';
        open my $phpconf_fh, '<', $phpconf;
        while (<$phpconf_fh>) {
            if (/^php5:[ \t]+['"]?([^'"]+)/) {
                $php5handler = $1;
            }
	}
	close $phpconf_fh;
        chomp $php5handler;
        if ( $php5handler eq "suphp" ) {
            print_info("[INFO] * ");
            print_normal("PHP5's handler is suPHP.\n");
        }
	print_warning("[WARN] * PHP5's handler is $php5handler.\n")
          if $php5handler ne "suphp";
    }
```

EA4 doesn't have a `php.conf.yaml`. 

Maybe you could do a check, if `/usr/local/apache/conf/php.conf.yaml` doesn't exist, check for `/etc/cpanel/ea4/php.conf` and grab the value(s) from here:
```
# cat php.conf
---
default: ea-php56
ea-php54: cgi
ea-php55: cgi
ea-php56: cgi
ea-php70: dso
```
