### ISSUE TITLE
Mailbox filter check should test for if the filter file is empty

### ISSUE THREAD

**Issue by betwixt-hexes** [CpanelInc/tech-SSE#21]
Currently the test for filter entries that exist under a mailbox just checks for the file itself and more-and-more often we're seeing these files are in place with nothing in them, making this a red herring while troubleshooting.

This test should be updated to ideally:

Confirm the file is empty or not empty for spitting out this info.
And maybe indicate *which* files matched.

**Comment by suedeyoung** [comment]
I'm hoping that the pull request to https://github.com/CpanelInc/tech-SSE/pull/24 will be able to help cut down the number of red herrings as it was able to cut it down fully for me for that flag. 

Based on the coding for the --email flag it checked the cPanel's accounts /etc/{emailaddressdomain}/{emailuser}/filter so if the message shows up while using the --email flag it should always be in that path unless I'm misreading it.
